---
- name: start-nginx
  service:
    name: nginx
    state: started 
  become: yes

- name: stop-nginx
  service:
    name: nginx
    state: stop
  become: yes

- name: restart-nginx
  service:
    name: nginx
    state: restarted
  become: yes
