---
# Do you think "Start the nginx service" will run this time?
# Handlers are nothing but tasks that get triggered by
# a "notify"
- hosts: webservers
  vars:
    our_desired_package_name: nginx
  tasks:
  - name: Make sure all OS patches are applied
    shell: yum update -y
    sudo: yes 
  - name: Install our needed packages for AWS Linux
    yum: state=present name={{ our_desired_package_name }}
    sudo: yes
  handlers:
  - name: Start the nginx service
    service: state=started name=nginx
    sudo: yes
