---
- hosts: demoserver
  tasks:
    - name: Show how errors can be ignored
      shell: ls /gobbledygook_file_that_does_not_exist
      ignore_errors: true
    - name: Another simple command
      debug: msg="Do you see this?"
